/** Release notes for the admin, newest first (Support → Updates and the ✨ menu). */
export type ReleaseTag = 'New' | 'Improved' | 'Fixed'
export interface Release { date: string; title: string; body: string; tag: ReleaseTag; area: string; to?: string }

export const RELEASES: Release[] = [
  { date: '2026-10-10', tag: 'New', area: 'Settings', title: 'Device approvals, app integrations and VoiceDrive PBX',
    body: 'Require admin approval when staff sign in from a new device. See every connected service on one page. Connect a cloud PBX for a call log and one-click calling.', to: '/admin/settings/devices' },
  { date: '2026-10-10', tag: 'New', area: 'Support', title: 'Bug reports, feedback and system status',
    body: 'Follow your bug reports and ideas with replies from the team, read the help center, and check that every part of the system is running.', to: '/admin/support/bugs' },
  { date: '2026-10-10', tag: 'New', area: 'Settings', title: 'Order sources, merchant profile and advanced settings',
    body: 'Add your own order sources (TikTok Live, Daraz…) and see orders, delivery rate and value per source. Keep owner, legal and payout details in one private place.', to: '/admin/settings?tab=sources' },
  { date: '2026-10-10', tag: 'New', area: 'HRM', title: 'HR: attendance, shifts, departments & SOPs',
    body: 'Staff check in and out themselves; late minutes count from their shift. HR dashboard, monthly report, shift planner, departments with SOPs and holidays.', to: '/admin/hr' },
  { date: '2026-10-10', tag: 'New', area: 'Customers', title: 'District map of your customers',
    body: 'A map of all 64 districts coloured by customers, orders or delivered value, with tools to fill in missing districts.', to: '/admin/customers?tab=map' },
  { date: '2026-10-10', tag: 'New', area: 'Inventory', title: 'Low stock alerts with reorder suggestions',
    body: 'Daily sales speed per product, days of stock left, how much to order, dead stock, ABC analysis and a 30-day forecast. Create a purchase order from the suggestions.', to: '/admin/inventory?view=alerts' },
  { date: '2026-10-10', tag: 'New', area: 'Orders', title: 'Actions menu and duplicate check on Approved Orders',
    body: 'Print, change status, book couriers and tag from one menu; find duplicate orders by phone and pick which copies to keep.', to: '/admin/orders/approved' },
  { date: '2026-10-10', tag: 'Fixed', area: 'Stock', title: 'Stock is never counted twice',
    body: 'A Shopify restock for an order already returned here, or a change that arrives during a sync, no longer adds stock twice.' },
  { date: '2026-10-10', tag: 'Improved', area: 'Orders', title: 'Delivered is final',
    body: 'A delivered parcel cannot be scanned in as a return by mistake. One Return pending tab; Pending cancel orders show under Cancelled.' },
  { date: '2026-10-10', tag: 'New', area: 'Store', title: 'Shopify order sync v3',
    body: 'Store orders merge with duplicates, statuses go back to Shopify, two-way stock, and honest attribution (Paid / Organic / Direct / Unknown).', to: '/admin/store/sync' },
  { date: '2026-10-10', tag: 'New', area: 'Store', title: 'Custom domains and a website API',
    body: 'Use your own domain for the store, or connect a custom-coded website with origin-locked API keys and the same secure checkout.', to: '/admin/store/website' },
  { date: '2026-10-10', tag: 'Improved', area: 'Couriers', title: 'Courier management',
    body: 'In-transit tab, courier age and attempt filters, call log, return management and analysis; RedX pickup stores.', to: '/admin/courier-management' },
  { date: '2026-10-09', tag: 'New', area: 'Store', title: 'Shopify and WooCommerce',
    body: 'Connect your stores: orders import automatically, stock syncs both ways, and fulfilment goes back with the tracking number.', to: '/admin/channels' },
  { date: '2026-10-09', tag: 'New', area: 'Marketing', title: 'Meta, TikTok and Google Ads',
    body: 'Daily ad spend from every account, profit per campaign and campaign quality.', to: '/admin/ads' },
  { date: '2026-10-09', tag: 'New', area: 'Admin', title: 'New menu, quick search and light mode',
    body: 'Web Orders and Approved Orders have their own menus with live counts. Ctrl+K finds orders, phones, consignment IDs, invoices, customers and SKUs. Choose light, dark or system colours.' },
  { date: '2026-10-09', tag: 'New', area: 'Fraud', title: 'BD Courier fraud check',
    body: 'Connect a BD Courier API key: parcels per courier and fraud reports from other merchants, checked when the customer types their number.', to: '/admin/settings?tab=fraud' },
  { date: '2026-10-03', tag: 'New', area: 'SMS', title: 'SMS automations',
    body: 'Order, shipping and payment messages with conditions, delivery reports and SMS cost in finance.', to: '/admin/sms' },
  { date: '2026-10-03', tag: 'New', area: 'Couriers', title: 'Courier webhooks and statements',
    body: 'Pathao status updates arrive by webhook, every event is logged, and courier statements are checked against your own records.', to: '/admin/couriers' },
  { date: '2026-10-03', tag: 'New', area: 'Payments', title: 'bKash and PayStation',
    body: 'Customers pay the advance online; payments are confirmed by the gateway on the server, never by the browser.', to: '/admin/settings?tab=payments' },
]
